package edu.neit.jonathandoolittle.models.sales;

import edu.neit.jonathandoolittle.models.tax.TaxModel;

/**
 * 
 * Represents a sales model used to model
 * the revenue generated by Harry Potter IV
 *
 * @author Jonathan Doolittle
 * @version 0.1 - Aug 17, 2021
 *
 */
public class HarryPotterSalesModel implements SalesModel {

	// ******************************
	// Variables
	// ******************************

	float unitPrice = 80.0f;
	
	// ******************************
	// Overrides
	// ******************************
	
	@Override
	public float reportRevenue(int units, TaxModel taxModel) {
		return units * (unitPrice + taxModel.getSalesTax(unitPrice));
	}

}
